### ISSUE TITLE
Demande_1

### ISSUE THREAD

**Issue by InasMahloul** [Emsi-students-2023/python-exercises#13]

**Comment by HamzaJamalDev** [comment]
Quel exercice voulez-vous travailler?

**Comment by InasMahloul** [comment]
Ex 9 et 13 et 18

**Comment by InasMahloul** [comment]
Bonjour monsieur;
Vous m'avez pas encore assigné les exercices

Le mer. 15 mars 2023 à 18:43, Hamza Jamal ***@***.***> a
écrit :
