### ISSUE TITLE
Demande de faire exercice 6 supplémentaire

### ISSUE THREAD

**Issue by AitWaarabImad** [Emsi-students-2023/python-exercises#19]

**Comment by HamzaJamalDev** [comment]
quel exercice?

**Comment by HamzaJamalDev** [comment]
cet exercice est déjà attribué à une autre personne.

**Comment by HamzaJamalDev** [comment]
Prenez un exercice non attribué : https://github.com/Emsi-students-2023/python-exercises#exercices-suppl%C3%A9mentaires-bonus-15

**Comment by AitWaarabImad** [comment]
Monsieur cet exercice n'est attribué à personne, et au moment où j'ai demandé de le faire il n'y avait aucune demande pour le faire.
