### ISSUE TITLE
Exercices du cours && Exercices supplémentaires

### ISSUE THREAD

**Issue by oussama166** [Emsi-students-2023/python-exercises#7]

**Comment by HamzaJamalDev** [comment]
Quel exercice voulez-vous travailler?

**Comment by oussama166** [comment]
J'ai travaillé toute les exes


Le mar. 21 mars 2023 à 8:35 AM, Hamza Jamal ***@***.***> a
écrit :

**Comment by oussama166** [comment]
9 && 13 && 18 (Exercices supplémentaires)
